# Netlify Configuration for Blobs Storage

[build]
  command = "npm run build"
  publish = "dist"

# Настройки для Edge Functions
[[edge_functions]]
  path = "/api/blobs"
  function = "blobs-api"

# ВАЖНО: Переменные окружения настраиваются в Netlify Dashboard
# Site settings → Environment variables
# Нужны: NETLIFY_BLOBS_TOKEN, SITE_ID
# Не храните токены в этом файле!
