# Netlify Configuration for Blobs Storage

[build]
  command = "npm run build"
  publish = "dist"

# Настройки для Edge Functions
[[edge_functions]]
  path = "/api/blobs"
  function = "blobs-api"

# ВАЖНО: Переменные окружения настраиваются в Netlify Dashboard
# Site settings → Environment variables
# Нужны: VITE_NETLIFY_SITE_ID, VITE_NETLIFY_BLOBS_TOKEN
# Не храните токены в этом файле!
