# Netlify Configuration for Blobs Storage

[build]
  command = "npm run build"
  publish = "dist"

# Настройки для Blobs Storage
[functions]
  directory = "netlify/functions"

# ВАЖНО: Переменные окружения настраиваются в Netlify Dashboard
# Site settings → Environment variables
# Не храните токены в этом файле!
